#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/ucsdlib/gps-py2017"
workshop_site   : "http://ucsdlib.github.io/gps-py2017"
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog        : "http://software-carpentry.org/feed.xml"
swc_contact     : "admin@software-carpentry.org"
swc_files       : "http://files.software-carpentry.org"
swc_github      : "http://github.com/swcarpentry"
swc_githubio    : "http://swcarpentry.github.io/"
swc_installer   : "https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe"
swc_site        : "http://software-carpentry.org"
swc_twitter     : "http://twitter.com/swcarpentry"
swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
swc_pre_survey  : "https://www.surveymonkey.com/r/swc_pre_workshop_v1?workshop_id="
swc_post_survey : "https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id="

#--------------------------------------------------------------------------------
# UCSD Library Workshop settings - including Department partners
#--------------------------------------------------------------------------------
lib_site        : "http://libraries.ucsd.edu"
lib_rdcp        : "http://libraries.ucsd.edu/rdcp"
lib_data_svcs   : "http://ucsd.libguides.com/data-services"
gps_site        : "http://gps.ucsd.edu"
lib_contact     : "timdennis@ucsd.edu"
lib_appt        : "https://calendly.com/tim-dennis/"

#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
